/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'planning' : IDL.Null,
});
export const View = IDL.Record({
  'id' : IDL.Nat,
  'status' : Type,
  'title' : IDL.Text,
  'assignedInterns' : IDL.Vec(IDL.Principal),
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'startDate' : IDL.Text,
});
export const View__3 = IDL.Record({
  'id' : IDL.Nat,
  'internPrincipal' : IDL.Principal,
  'title' : IDL.Text,
  'hours' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
});
export const Type__1 = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const View__2 = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'registrationStatus' : Type__1,
  'skills' : IDL.Vec(IDL.Text),
});
export const View__1 = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Type__2 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveInternRegistration' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignInternToProject' : IDL.Func(
      [
        IDL.Record({
          'internPrincipal' : IDL.Principal,
          'projectId' : IDL.Nat,
        }),
      ],
      [],
      [],
    ),
  'createProject' : IDL.Func(
      [
        IDL.Record({
          'title' : IDL.Text,
          'endDate' : IDL.Text,
          'description' : IDL.Text,
          'startDate' : IDL.Text,
        }),
      ],
      [View],
      [],
    ),
  'getActivitiesForIntern' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(View__3)],
      ['query'],
    ),
  'getActivitiesForProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(View__3)],
      ['query'],
    ),
  'getAllActivities' : IDL.Func([], [IDL.Vec(View__3)], ['query']),
  'getAllInterns' : IDL.Func([], [IDL.Vec(View__2)], ['query']),
  'getAllPendingInterns' : IDL.Func([], [IDL.Vec(View__2)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(View)], ['query']),
  'getAllRejectedInterns' : IDL.Func([], [IDL.Vec(View__2)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(View__2)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(View__2)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(View__1)], ['query']),
  'getMessagesForCaller' : IDL.Func([], [IDL.Vec(View__1)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(View)], ['query']),
  'getProjectsByStatus' : IDL.Func([Type], [IDL.Vec(View)], ['query']),
  'getProjectsForIntern' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(View)],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(View__2)], ['query']),
  'getUserRole' : IDL.Func([IDL.Principal], [Type__2], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logActivity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [View__3],
      [],
    ),
  'markMessageRead' : IDL.Func([IDL.Nat], [], []),
  'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
  'registerIntern' : IDL.Func(
      [IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text, 'email' : IDL.Text })],
      [],
      [],
    ),
  'rejectInternRegistration' : IDL.Func([IDL.Principal], [], []),
  'removeProject' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([View__2], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [View__1], []),
  'unassignInternFromProject' : IDL.Func(
      [
        IDL.Record({
          'internPrincipal' : IDL.Principal,
          'projectId' : IDL.Nat,
        }),
      ],
      [],
      [],
    ),
  'updateProfile' : IDL.Func(
      [
        IDL.Record({
          'bio' : IDL.Text,
          'name' : IDL.Text,
          'email' : IDL.Text,
          'skills' : IDL.Vec(IDL.Text),
        }),
      ],
      [],
      [],
    ),
  'updateProject' : IDL.Func([View], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'planning' : IDL.Null,
  });
  const View = IDL.Record({
    'id' : IDL.Nat,
    'status' : Type,
    'title' : IDL.Text,
    'assignedInterns' : IDL.Vec(IDL.Principal),
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const View__3 = IDL.Record({
    'id' : IDL.Nat,
    'internPrincipal' : IDL.Principal,
    'title' : IDL.Text,
    'hours' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
  });
  const Type__1 = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const View__2 = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'registrationStatus' : Type__1,
    'skills' : IDL.Vec(IDL.Text),
  });
  const View__1 = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Type__2 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveInternRegistration' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignInternToProject' : IDL.Func(
        [
          IDL.Record({
            'internPrincipal' : IDL.Principal,
            'projectId' : IDL.Nat,
          }),
        ],
        [],
        [],
      ),
    'createProject' : IDL.Func(
        [
          IDL.Record({
            'title' : IDL.Text,
            'endDate' : IDL.Text,
            'description' : IDL.Text,
            'startDate' : IDL.Text,
          }),
        ],
        [View],
        [],
      ),
    'getActivitiesForIntern' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(View__3)],
        ['query'],
      ),
    'getActivitiesForProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(View__3)],
        ['query'],
      ),
    'getAllActivities' : IDL.Func([], [IDL.Vec(View__3)], ['query']),
    'getAllInterns' : IDL.Func([], [IDL.Vec(View__2)], ['query']),
    'getAllPendingInterns' : IDL.Func([], [IDL.Vec(View__2)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(View)], ['query']),
    'getAllRejectedInterns' : IDL.Func([], [IDL.Vec(View__2)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(View__2)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(View__2)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(View__1)],
        ['query'],
      ),
    'getMessagesForCaller' : IDL.Func([], [IDL.Vec(View__1)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(View)], ['query']),
    'getProjectsByStatus' : IDL.Func([Type], [IDL.Vec(View)], ['query']),
    'getProjectsForIntern' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(View)],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(View__2)], ['query']),
    'getUserRole' : IDL.Func([IDL.Principal], [Type__2], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logActivity' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [View__3],
        [],
      ),
    'markMessageRead' : IDL.Func([IDL.Nat], [], []),
    'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
    'registerIntern' : IDL.Func(
        [
          IDL.Record({
            'bio' : IDL.Text,
            'name' : IDL.Text,
            'email' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'rejectInternRegistration' : IDL.Func([IDL.Principal], [], []),
    'removeProject' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([View__2], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [View__1], []),
    'unassignInternFromProject' : IDL.Func(
        [
          IDL.Record({
            'internPrincipal' : IDL.Principal,
            'projectId' : IDL.Nat,
          }),
        ],
        [],
        [],
      ),
    'updateProfile' : IDL.Func(
        [
          IDL.Record({
            'bio' : IDL.Text,
            'name' : IDL.Text,
            'email' : IDL.Text,
            'skills' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
        [],
      ),
    'updateProject' : IDL.Func([View], [], []),
  });
};

export const init = ({ IDL }) => { return []; };