/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Type = { 'active' : null } |
  { 'completed' : null } |
  { 'planning' : null };
export type Type__1 = { 'active' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export type Type__2 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface View {
  'id' : bigint,
  'status' : Type,
  'title' : string,
  'assignedInterns' : Array<Principal>,
  'endDate' : string,
  'description' : string,
  'startDate' : string,
}
export interface View__1 {
  'id' : bigint,
  'content' : string,
  'recipient' : Principal,
  'isRead' : boolean,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface View__2 {
  'bio' : string,
  'principal' : Principal,
  'name' : string,
  'email' : string,
  'registrationStatus' : Type__1,
  'skills' : Array<string>,
}
export interface View__3 {
  'id' : bigint,
  'internPrincipal' : Principal,
  'title' : string,
  'hours' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'description' : string,
  'projectId' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveInternRegistration' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignInternToProject' : ActorMethod<
    [{ 'internPrincipal' : Principal, 'projectId' : bigint }],
    undefined
  >,
  'createProject' : ActorMethod<
    [
      {
        'title' : string,
        'endDate' : string,
        'description' : string,
        'startDate' : string,
      },
    ],
    View
  >,
  'getActivitiesForIntern' : ActorMethod<[Principal], Array<View__3>>,
  'getActivitiesForProject' : ActorMethod<[bigint], Array<View__3>>,
  'getAllActivities' : ActorMethod<[], Array<View__3>>,
  'getAllInterns' : ActorMethod<[], Array<View__2>>,
  'getAllPendingInterns' : ActorMethod<[], Array<View__2>>,
  'getAllProjects' : ActorMethod<[], Array<View>>,
  'getAllRejectedInterns' : ActorMethod<[], Array<View__2>>,
  'getAllUsers' : ActorMethod<[], Array<View__2>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [View__2]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<View__1>>,
  'getMessagesForCaller' : ActorMethod<[], Array<View__1>>,
  'getProject' : ActorMethod<[bigint], [] | [View]>,
  'getProjectsByStatus' : ActorMethod<[Type], Array<View>>,
  'getProjectsForIntern' : ActorMethod<[Principal], Array<View>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [View__2]>,
  'getUserRole' : ActorMethod<[Principal], Type__2>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logActivity' : ActorMethod<
    [bigint, string, string, string, bigint],
    View__3
  >,
  'markMessageRead' : ActorMethod<[bigint], undefined>,
  'promoteToAdmin' : ActorMethod<[Principal], undefined>,
  'registerIntern' : ActorMethod<
    [{ 'bio' : string, 'name' : string, 'email' : string }],
    undefined
  >,
  'rejectInternRegistration' : ActorMethod<[Principal], undefined>,
  'removeProject' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[View__2], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], View__1>,
  'unassignInternFromProject' : ActorMethod<
    [{ 'internPrincipal' : Principal, 'projectId' : bigint }],
    undefined
  >,
  'updateProfile' : ActorMethod<
    [
      {
        'bio' : string,
        'name' : string,
        'email' : string,
        'skills' : Array<string>,
      },
    ],
    undefined
  >,
  'updateProject' : ActorMethod<[View], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];