/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface View__3 {
    id: bigint;
    internPrincipal: Principal;
    title: string;
    hours: bigint;
    date: string;
    createdAt: bigint;
    description: string;
    projectId: bigint;
}
export interface View__2 {
    bio: string;
    principal: Principal;
    name: string;
    email: string;
    registrationStatus: Type__2;
    skills: Array<string>;
}
export interface View__5 {
    id: bigint;
    internPrincipal: Principal;
    status: Type__1;
    title: string;
    createdAt: bigint;
    dueDate: string;
    description: string;
    projectId: bigint;
}
export interface View__4 {
    id: bigint;
    notificationType: Type__4;
    isRead: boolean;
    message: string;
    timestamp: bigint;
    relatedId: bigint;
    recipientPrincipal: Principal;
}
export interface Type__5 {
    totalActivities: bigint;
    totalHours: bigint;
    recentActivities: Array<View__3>;
    completedMilestones: bigint;
    hoursByProject: Array<[bigint, bigint]>;
    totalMilestones: bigint;
    projectCount: bigint;
    activeInternCount: bigint;
}
export interface View {
    id: bigint;
    status: Type;
    title: string;
    assignedInterns: Array<Principal>;
    endDate: string;
    description: string;
    startDate: string;
}
export interface View__1 {
    id: bigint;
    content: string;
    recipient: Principal;
    isRead: boolean;
    sender: Principal;
    timestamp: bigint;
}
export enum Type {
    active = "active",
    completed = "completed",
    planning = "planning"
}
export enum Type__1 {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum Type__2 {
    active = "active",
    pending = "pending",
    rejected = "rejected"
}
export enum Type__4 {
    projectAssigned = "projectAssigned",
    messageReceived = "messageReceived",
    newApprovalRequest = "newApprovalRequest",
    milestoneUpdate = "milestoneUpdate"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveInternRegistration(userPrincipal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignInternToProject(arg0: {
        internPrincipal: Principal;
        projectId: bigint;
    }): Promise<void>;
    createMilestone(arg0: {
        title: string;
        dueDate: string;
        description: string;
        projectId: bigint;
    }): Promise<View__5>;
    createProject(arg0: {
        title: string;
        endDate: string;
        description: string;
        startDate: string;
    }): Promise<View>;
    getActivitiesForIntern(intern: Principal): Promise<Array<View__3>>;
    getActivitiesForProject(projectId: bigint): Promise<Array<View__3>>;
    getAllActivities(): Promise<Array<View__3>>;
    getAllInterns(): Promise<Array<View__2>>;
    getAllMilestones(): Promise<Array<View__5>>;
    getAllPendingInterns(): Promise<Array<View__2>>;
    getAllProjects(): Promise<Array<View>>;
    getAllRejectedInterns(): Promise<Array<View__2>>;
    getAllUsers(): Promise<Array<View__2>>;
    getAnalyticsSummary(): Promise<Type__5>;
    getCallerUserProfile(): Promise<View__2 | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(otherUser: Principal): Promise<Array<View__1>>;
    getMessagesForCaller(): Promise<Array<View__1>>;
    getMilestonesForIntern(intern: Principal): Promise<Array<View__5>>;
    getMilestonesForProject(projectId: bigint): Promise<Array<View__5>>;
    getNotificationsForCaller(): Promise<Array<View__4>>;
    getProject(id: bigint): Promise<View | null>;
    getProjectsByStatus(status: Type): Promise<Array<View>>;
    getProjectsForIntern(intern: Principal): Promise<Array<View>>;
    getUnreadCount(): Promise<bigint>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<View__2 | null>;
    getUserRole(user: Principal): Promise<Type__3>;
    isCallerAdmin(): Promise<boolean>;
    logActivity(projectId: bigint, title: string, description: string, date: string, hours: bigint): Promise<View__3>;
    markAllNotificationsRead(): Promise<void>;
    markMessageRead(messageId: bigint): Promise<void>;
    markNotificationRead(notificationId: bigint): Promise<void>;
    promoteToAdmin(user: Principal): Promise<void>;
    registerIntern(arg0: {
        bio: string;
        name: string;
        email: string;
    }): Promise<void>;
    rejectInternRegistration(userPrincipal: Principal): Promise<void>;
    removeProject(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: View__2): Promise<void>;
    sendMessage(recipient: Principal, content: string): Promise<View__1>;
    unassignInternFromProject(arg0: {
        internPrincipal: Principal;
        projectId: bigint;
    }): Promise<void>;
    updateMilestoneStatus(milestoneId: bigint, status: Type__1): Promise<void>;
    updateProfile(arg0: {
        bio: string;
        name: string;
        email: string;
        skills: Array<string>;
    }): Promise<void>;
    updateProject(project: View): Promise<void>;
}
import type { Type as _Type, Type__1 as _Type__1, Type__2 as _Type__2, Type__3 as _Type__3, Type__4 as _Type__4, UserRole as _UserRole, View as _View, View__2 as _View__2, View__4 as _View__4, View__5 as _View__5 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveInternRegistration(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveInternRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveInternRegistration(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignInternToProject(arg0: {
        internPrincipal: Principal;
        projectId: bigint;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignInternToProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignInternToProject(arg0);
            return result;
        }
    }
    async createMilestone(arg0: {
        title: string;
        dueDate: string;
        description: string;
        projectId: bigint;
    }): Promise<View__5> {
        if (this.processError) {
            try {
                const result = await this.actor.createMilestone(arg0);
                return from_candid_View__5_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMilestone(arg0);
            return from_candid_View__5_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: {
        title: string;
        endDate: string;
        description: string;
        startDate: string;
    }): Promise<View> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0);
                return from_candid_View_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0);
            return from_candid_View_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivitiesForIntern(arg0: Principal): Promise<Array<View__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesForIntern(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesForIntern(arg0);
            return result;
        }
    }
    async getActivitiesForProject(arg0: bigint): Promise<Array<View__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesForProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesForProject(arg0);
            return result;
        }
    }
    async getAllActivities(): Promise<Array<View__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivities();
            return result;
        }
    }
    async getAllInterns(): Promise<Array<View__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInterns();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInterns();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMilestones(): Promise<Array<View__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMilestones();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMilestones();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingInterns(): Promise<Array<View__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingInterns();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingInterns();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<View>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRejectedInterns(): Promise<Array<View__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRejectedInterns();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRejectedInterns();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<View__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsSummary(): Promise<Type__5> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<View__2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Array<View__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getMessagesForCaller(): Promise<Array<View__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesForCaller();
            return result;
        }
    }
    async getMilestonesForIntern(arg0: Principal): Promise<Array<View__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilestonesForIntern(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilestonesForIntern(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMilestonesForProject(arg0: bigint): Promise<Array<View__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilestonesForProject(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilestonesForProject(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationsForCaller(): Promise<Array<View__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsForCaller();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsForCaller();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<View | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByStatus(arg0: Type): Promise<Array<View>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByStatus(to_candid_Type_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByStatus(to_candid_Type_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsForIntern(arg0: Principal): Promise<Array<View>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsForIntern(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsForIntern(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<View__2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<Type__3> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_Type__3_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_Type__3_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logActivity(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<View__3> {
        if (this.processError) {
            try {
                const result = await this.actor.logActivity(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logActivity(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markMessageRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageRead(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async promoteToAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteToAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteToAdmin(arg0);
            return result;
        }
    }
    async registerIntern(arg0: {
        bio: string;
        name: string;
        email: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerIntern(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerIntern(arg0);
            return result;
        }
    }
    async rejectInternRegistration(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectInternRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectInternRegistration(arg0);
            return result;
        }
    }
    async removeProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProject(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: View__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_View__2_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_View__2_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<View__1> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async unassignInternFromProject(arg0: {
        internPrincipal: Principal;
        projectId: bigint;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unassignInternFromProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unassignInternFromProject(arg0);
            return result;
        }
    }
    async updateMilestoneStatus(arg0: bigint, arg1: Type__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMilestoneStatus(arg0, to_candid_Type__1_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMilestoneStatus(arg0, to_candid_Type__1_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProfile(arg0: {
        bio: string;
        name: string;
        email: string;
        skills: Array<string>;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
    async updateProject(arg0: View): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(to_candid_View_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(to_candid_View_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Type__1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Type__2_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__2): Type__2 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Type__3_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__3): Type__3 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Type__4_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__4): Type__4 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_View__2_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _View__2): View__2 {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_View__4_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _View__4): View__4 {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_View__5_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _View__5): View__5 {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_View_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _View): View {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_View__2]): View__2 | null {
    return value.length === 0 ? null : from_candid_View__2_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_View]): View | null {
    return value.length === 0 ? null : from_candid_View_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    name: string;
    email: string;
    registrationStatus: _Type__2;
    skills: Array<string>;
}): {
    bio: string;
    principal: Principal;
    name: string;
    email: string;
    registrationStatus: Type__2;
    skills: Array<string>;
} {
    return {
        bio: value.bio,
        principal: value.principal,
        name: value.name,
        email: value.email,
        registrationStatus: from_candid_Type__2_n14(_uploadFile, _downloadFile, value.registrationStatus),
        skills: value.skills
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notificationType: _Type__4;
    isRead: boolean;
    message: string;
    timestamp: bigint;
    relatedId: bigint;
    recipientPrincipal: Principal;
}): {
    id: bigint;
    notificationType: Type__4;
    isRead: boolean;
    message: string;
    timestamp: bigint;
    relatedId: bigint;
    recipientPrincipal: Principal;
} {
    return {
        id: value.id,
        notificationType: from_candid_Type__4_n24(_uploadFile, _downloadFile, value.notificationType),
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp,
        relatedId: value.relatedId,
        recipientPrincipal: value.recipientPrincipal
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    internPrincipal: Principal;
    status: _Type__1;
    title: string;
    createdAt: bigint;
    dueDate: string;
    description: string;
    projectId: bigint;
}): {
    id: bigint;
    internPrincipal: Principal;
    status: Type__1;
    title: string;
    createdAt: bigint;
    dueDate: string;
    description: string;
    projectId: bigint;
} {
    return {
        id: value.id,
        internPrincipal: value.internPrincipal,
        status: from_candid_Type__1_n5(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        description: value.description,
        projectId: value.projectId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Type;
    title: string;
    assignedInterns: Array<Principal>;
    endDate: string;
    description: string;
    startDate: string;
}): {
    id: bigint;
    status: Type;
    title: string;
    assignedInterns: Array<Principal>;
    endDate: string;
    description: string;
    startDate: string;
} {
    return {
        id: value.id,
        status: from_candid_Type_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedInterns: value.assignedInterns,
        endDate: value.endDate,
        description: value.description,
        startDate: value.startDate
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    planning: null;
}): Type {
    return "active" in value ? Type.active : "completed" in value ? Type.completed : "planning" in value ? Type.planning : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    rejected: null;
}): Type__2 {
    return "active" in value ? Type__2.active : "pending" in value ? Type__2.pending : "rejected" in value ? Type__2.rejected : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectAssigned: null;
} | {
    messageReceived: null;
} | {
    newApprovalRequest: null;
} | {
    milestoneUpdate: null;
}): Type__4 {
    return "projectAssigned" in value ? Type__4.projectAssigned : "messageReceived" in value ? Type__4.messageReceived : "newApprovalRequest" in value ? Type__4.newApprovalRequest : "milestoneUpdate" in value ? Type__4.milestoneUpdate : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): Type__1 {
    return "pending" in value ? Type__1.pending : "completed" in value ? Type__1.completed : "inProgress" in value ? Type__1.inProgress : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_View__2>): Array<View__2> {
    return value.map((x)=>from_candid_View__2_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_View__5>): Array<View__5> {
    return value.map((x)=>from_candid_View__5_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_View>): Array<View> {
    return value.map((x)=>from_candid_View_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_View__4>): Array<View__4> {
    return value.map((x)=>from_candid_View__4_n22(_uploadFile, _downloadFile, x));
}
function to_candid_Type__1_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): _Type__1 {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Type__2_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): _Type__2 {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_View__2_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: View__2): _View__2 {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_View_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: View): _View {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    name: string;
    email: string;
    registrationStatus: Type__2;
    skills: Array<string>;
}): {
    bio: string;
    principal: Principal;
    name: string;
    email: string;
    registrationStatus: _Type__2;
    skills: Array<string>;
} {
    return {
        bio: value.bio,
        principal: value.principal,
        name: value.name,
        email: value.email,
        registrationStatus: to_candid_Type__2_n32(_uploadFile, _downloadFile, value.registrationStatus),
        skills: value.skills
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Type;
    title: string;
    assignedInterns: Array<Principal>;
    endDate: string;
    description: string;
    startDate: string;
}): {
    id: bigint;
    status: _Type;
    title: string;
    assignedInterns: Array<Principal>;
    endDate: string;
    description: string;
    startDate: string;
} {
    return {
        id: value.id,
        status: to_candid_Type_n27(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedInterns: value.assignedInterns,
        endDate: value.endDate,
        description: value.description,
        startDate: value.startDate
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    active: null;
} | {
    completed: null;
} | {
    planning: null;
} {
    return value == Type.active ? {
        active: null
    } : value == Type.completed ? {
        completed: null
    } : value == Type.planning ? {
        planning: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): {
    active: null;
} | {
    pending: null;
} | {
    rejected: null;
} {
    return value == Type__2.active ? {
        active: null
    } : value == Type__2.pending ? {
        pending: null
    } : value == Type__2.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == Type__1.pending ? {
        pending: null
    } : value == Type__1.completed ? {
        completed: null
    } : value == Type__1.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
